version: "3"
services:
  client:
    build: ./client
    ports:
      - "8080:8080"
  server:
    build: ./server
    ports:
      - "3090:3090"
  db:
    image: mongo:latest
    expose:
      - "27017"
